"""changed user and workspace

Revision ID: 25667a37e971
Revises: f5a03384a716
Create Date: 2026-08-11 21:50:06.519971

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '25667a37e971'
down_revision = 'f5a03384a716'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('clerk_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_user_clerk_id'), 'user', ['clerk_id'], unique=False)
    op.add_column('workspace', sa.Column('public_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_workspace_public_id'), 'workspace', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_public_id'), table_name='workspace')
    op.drop_column('workspace', 'public_id')
    op.drop_index(op.f('ix_user_clerk_id'), table_name='user')
    op.drop_column('user', 'clerk_id')
    # ### end Alembic commands ###
