"""public_id for chat and messages

Revision ID: 2a6c08051a8d
Revises: b73da773eb1c
Create Date: 2026-09-01 20:05:10.253379

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2a6c08051a8d'
down_revision = 'b73da773eb1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('public_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_chat_public_id'), 'chat', ['public_id'], unique=True)
    op.add_column('message', sa.Column('public_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_message_public_id'), 'message', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_public_id'), table_name='message')
    op.drop_column('message', 'public_id')
    op.drop_index(op.f('ix_chat_public_id'), table_name='chat')
    op.drop_column('chat', 'public_id')
    # ### end Alembic commands ###
