"""fixed chunks relationship error

Revision ID: 34007886fe9a
Revises: 57899302d08b
Create Date: 2026-08-19 20:43:26.869824

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '34007886fe9a'
down_revision = '57899302d08b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
