"""updated messsage

Revision ID: 406a72b3b5de
Revises: 2a6c08051a8d
Create Date: 2026-09-04 00:02:34.357030

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '406a72b3b5de'
down_revision = '2a6c08051a8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
