"""embeddings

Revision ID: 57899302d08b
Revises: 649393362aee
Create Date: 2026-08-19 20:31:14.784014

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector 


# revision identifiers, used by Alembic.
revision = '57899302d08b'
down_revision = '649393362aee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunk_created_at'), 'chunk', ['created_at'], unique=False)
    op.create_index(op.f('ix_chunk_file_id'), 'chunk', ['file_id'], unique=False)
    op.create_index(op.f('ix_chunk_id'), 'chunk', ['id'], unique=False)
    op.create_index(op.f('ix_chunk_workspace_id'), 'chunk', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_workspace_id'), table_name='chunk')
    op.drop_index(op.f('ix_chunk_id'), table_name='chunk')
    op.drop_index(op.f('ix_chunk_file_id'), table_name='chunk')
    op.drop_index(op.f('ix_chunk_created_at'), table_name='chunk')
    op.drop_table('chunk')
    # ### end Alembic commands ###
