"""added files

Revision ID: 649393362aee
Revises: 25667a37e971
Create Date: 2026-08-14 15:03:24.059971

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '649393362aee'
down_revision = '25667a37e971'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_created_at'), 'file', ['created_at'], unique=False)
    op.create_index(op.f('ix_file_file_type'), 'file', ['file_type'], unique=False)
    op.create_index(op.f('ix_file_filename'), 'file', ['filename'], unique=False)
    op.create_index(op.f('ix_file_id'), 'file', ['id'], unique=False)
    op.create_index(op.f('ix_file_public_id'), 'file', ['public_id'], unique=True)
    op.create_index(op.f('ix_file_updated_at'), 'file', ['updated_at'], unique=False)
    op.create_index(op.f('ix_file_workspace_id'), 'file', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_workspace_id'), table_name='file')
    op.drop_index(op.f('ix_file_updated_at'), table_name='file')
    op.drop_index(op.f('ix_file_public_id'), table_name='file')
    op.drop_index(op.f('ix_file_id'), table_name='file')
    op.drop_index(op.f('ix_file_filename'), table_name='file')
    op.drop_index(op.f('ix_file_file_type'), table_name='file')
    op.drop_index(op.f('ix_file_created_at'), table_name='file')
    op.drop_table('file')
    # ### end Alembic commands ###
