"""initial schema

Revision ID: f5a03384a716
Revises: 
Create Date: 2026-08-10 22:10:40.547096

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f5a03384a716'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('workspace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_created_at'), 'workspace', ['created_at'], unique=False)
    op.create_index(op.f('ix_workspace_id'), 'workspace', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_name'), 'workspace', ['name'], unique=False)
    op.create_index(op.f('ix_workspace_updated_at'), 'workspace', ['updated_at'], unique=False)
    op.create_index(op.f('ix_workspace_user_id'), 'workspace', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_user_id'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_updated_at'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_name'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_id'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_created_at'), table_name='workspace')
    op.drop_table('workspace')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
